const UPDATE_USER_PROFILE = "user:UPDATE_USER_PROFILE";
const UPDATE_USER_PASSWORD = "user:UPDATE_USER_PASSWORD";
const DEACTIVATE_ACCOUNT = "user:DEACTIVATE_ACCOUNT";

const BLOCK_USER = "admin:BLOCK_USER";

const ADD_ADMIN = "superAdmin:ADD_ADMIN";
const DELETE_ADMIN = "superAdmin:DELETE_ADMIN";
const GET_ALL_ADMINS = "superAdmin:GET_ALL_ADMINS";
const UPDATE_ADMIN = "superAdmin:UPDATE_ADMIN";


module.exports={
    UPDATE_USER_PROFILE,
    UPDATE_USER_PASSWORD,
    DEACTIVATE_ACCOUNT,
    BLOCK_USER,
    ADD_ADMIN,
    DELETE_ADMIN,
    GET_ALL_ADMINS,
    UPDATE_ADMIN
}



